//-------------------------------------------------------Library of Pictures-----------------------------------------
const library = {
  "1-1.1":[
       {
         prompt: "If I say “안녕하세요, you can respond with: (hello)",
         image: "helloHowAreYou.jpg",
         alt: "Words:Say hello to others",
         credit: `<span>Photo by <a href="https://unsplash.com/@kevin_butz?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Kevin Butz</a> on <a href="https://unsplash.com/s/photos/hello?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
         answer: "안녕하세요",
       },
       {
         prompt: "If I do something nice for you, you can respond with: (thank you)",
         image: "thankyou.jpg",
         alt: "Picture of the words Thank You",
         credit: `<span>Photo by <a href="https://unsplash.com/@element5digital?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Element5 Digital</a> on <a href="https://unsplash.com/s/photos/student?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
         answer: "감사합니다",
       },
       {
         prompt: "If you agree to something you can say: (yes)",
         image: "yes.jpg",
         alt: "Picture of the word yes",
         credit: `<span>Photo by <a href="https://unsplash.com/@shelly94?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Michèle Eckert</a> on <a href="https://unsplash.com/s/photos/yes?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
         answer: "네",
       },
       {
         prompt: "If you disagree with something, you can say (no)",
         image: "no.jpg",
         alt: "Picture of the word no",
         credit: `<span>Photo by <a href="https://unsplash.com/@stayandroam?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Gemma Evans</a> on <a href="https://unsplash.com/s/photos/no?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
         answer: "아니요",
       },
       {
         prompt: "If you want something, to be polite you can say: (please)",
         image: "please.jpg",
         alt: "hands saying please",
         credit: `<span>Photo by <a href="https://unsplash.com/@fan11?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Fa Barboza</a> on <a href="https://unsplash.com/s/photos/pray?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
         answer: "제발",
       },
       {
         prompt: "If you are this person, you are who? (woman)",
         image: "iAmAWoman.jpg",
         alt: "Picture of Woman",
         credit: `<span>Photo by <a href="https://unsplash.com/@tyfeague?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Ty Feague</a> on <a href="https://unsplash.com/s/photos/woman-points-to-herself?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
         answer: "저는 여자예요",
       },
       {
         prompt: "If you are this person, you are who? (teacher)",
         image: "iAmATeacher.jpg",
         alt: "Picture of Teacher",
         credit: `<span>Photo by <a href="https://unsplash.com/@windows?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Windows</a> on <a href="https://unsplash.com/s/photos/teacher-points-to-herself?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
         answer: " 저는 선생님이에요",
       },
       {
         prompt: "Are you a person? (yes...person)",
         image: "iAmAPerson.jpg",
         alt: "Guy points to himself",
         credit: `<span>Photo by <a href="https://unsplash.com/@christianbuehner?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">christian buehner</a> on <a href="https://unsplash.com/s/photos/man-points-to-himself?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
         answer: "저는 사람이에요",
       },
       {
         prompt: "Who is that person? (man)",
         image: "iAmAPerson.jpg",
         alt: "Guy points to himself",
         credit: `<span>Photo by <a href="https://unsplash.com/@christianbuehner?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">christian buehner</a> on <a href="https://unsplash.com/s/photos/man-points-to-himself?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
         answer: "그 사람은 남자예요",
       },
       {
         prompt: "Who is that person? (doctor)",
         image: "thatPersonIsADoctor.jpg",
         alt: "Picture of a Doctor",
         credit: `<span>Photo by <a href="https://unsplash.com/@jcgellidon?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">JC Gellidon</a> on <a href="https://unsplash.com/s/photos/doctor?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
         answer: "그 사람은 의사예요",
       },
       {
         prompt: "Who is that person? (woman)",
         image: "iAmAWoman.jpg",
         alt: "Picture of Woman",
         credit: `<span>Photo by <a href="https://unsplash.com/@tyfeague?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Ty Feague</a> on <a href="https://unsplash.com/s/photos/woman-points-to-herself?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
         answer: "그 사람은 여자예요",
       },
       {
         prompt: "Who is this person? (doctor)",
         image: "thatPersonIsADoctor.jpg",
         alt: "Picture of a Doctor",
         credit: `<span>Photo by <a href="https://unsplash.com/@jcgellidon?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">JC Gellidon</a> on <a href="https://unsplash.com/s/photos/doctor?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
         answer: "그 사람은 선생님이에요",
       },
       {
         prompt: "Who is that person? (student)",
         image: "thisIsAStudent.jpg",
         alt: "Picture of a student",
         credit: `<span>Photo by <a href="https://unsplash.com/@element5digital?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Element5 Digital</a> on <a href="https://unsplash.com/s/photos/student?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
         answer: "그 사람은 학생이에요",
       },
       {
         prompt: "What is this? (tree)",
         image: "thatIsATree.jpg",
         alt: "Picture of a Tree",
         credit: `<span>Photo by <a href="https://unsplash.com/@fabulu75?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Fabrice Villard</a> on <a href="https://unsplash.com/s/photos/tree?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
         answer: "이것은 나무예요",
       },
       {
         prompt: "What is this (table)",
         image: "thatIsATable.jpg",
         alt: "Picture of a table",
         credit: `<span>Photo by <a href="https://unsplash.com/@olenkasergienko?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Olena Sergienko</a> on <a href="https://unsplash.com/s/photos/table?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
         answer: "이것은 탁자예요",
       },
       {
         prompt: "What is that? (bed)",
         image: "thatIsABed.jpg",
         alt: "Picture of a bed",
         credit: `<span>Photo by <a href="https://unsplash.com/@neonbrand?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">NeONBRAND</a> on <a href="https://unsplash.com/s/photos/bed?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
         answer: "저것은 침대예요",
       },
       {
         prompt: "What is that? (car)",
         image: "thatIsACar.jpg",
         alt: "Picture of a Car",
         credit: `<span>Photo by <a href="https://unsplash.com/@eduardoflorespe?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Eduardo Flores</a> on <a href="https://unsplash.com/s/photos/car?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
         answer: "그것은 차예요",
       },
     ], //need to fill in more blanks starting from here
     "1-1.2":[
       {
         prompt: "What country is this? (korea).  Is this a city?",
         image: "thisIsKorea.jpg",
         alt: "Picture of Korean city",
         credit: `<span>Photo by <a href="https://unsplash.com/@dandycolor?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Saveliy Bobov</a> on <a href="https://unsplash.com/s/photos/korea?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
         answer: "이것은 한국이에요  (네, 이것은 도시예요) ",
     
       },
       {
         prompt: "What country is this? (China)",
         image: "thatIsChina.jpg",
         alt: "Picture of China",
         credit: `<span>Photo by <a href="https://unsplash.com/@chuttersnap?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">CHUTTERSNAP</a> on <a href="https://unsplash.com/s/photos/china?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
         answer: "이것은 중국이에요",
     
       },
       {
         prompt: "What country is this? (Japan)",
         image: "thisIsJapan.jpg",
         alt: "Picture of Japan",
         credit: `<span>Photo by <a href="https://unsplash.com/@nicki_schinow?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Nicki Eliza Schinow</a> on <a href="https://unsplash.com/s/photos/japan?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
         answer: "이것은 일본이에요",
       },
       {
         prompt: "What is that? (a house)",
         image: "thisIsAHouse.jpg",
         alt: "Picture of a house",
         credit: `<span>Photo by <a href="https://unsplash.com/@jacquesbopp?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Jacques Bopp</a> on <a href="https://unsplash.com/s/photos/house?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
         answer: "저것은 집이에요",
       },
       {
         prompt: "What is this? (name)",
         image: "thatIsAName.jpg",
         alt: "Picture of a name on a name tag",
         credit: `<span>Photo by <a href="https://unsplash.com/@_blahblake?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Blake Barlow</a> on <a href="https://unsplash.com/s/photos/name-tag?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
         answer: "이것은 이름이에요",
       },
       {
         prompt: "What is that? (a chair)",
         image: "thatIsAChair.jpg",
         alt: "Picture of a chair",
         credit: `<span>Photo by <a href="https://unsplash.com/@andresloquesea?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Andrés Gómez</a> on <a href="https://unsplash.com/s/photos/chair?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
         answer: "저것은 의자예요",
       },
       {
         prompt: "What is this? (book)",
         image: "thisIsABook.jpg",
         alt: "Picture of a Book",
         credit: `<span>Photo by <a href="https://unsplash.com/@blazphoto?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Blaz Photo</a> on <a href="https://unsplash.com/s/photos/book?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
         answer: "이것은 책이에요",
       },
       {
         prompt: "What is that? (a computer)",
         image: "thisIsAComputer.jpg",
         alt: "Picture of a computer",
         credit: `<span>Photo by <a href="https://unsplash.com/@nicklbaert?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Niclas Illg</a> on <a href="https://unsplash.com/s/photos/computer?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
         answer: "저것은 컴퓨너예요",
       },
       {
         prompt: "What is this? (sofa)",
         image: "thatIsASofa.jpg",
         alt: "Picture of a sofa",
         credit: `<span>Photo by <a href="https://unsplash.com/@paulweaver?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Paul Weaver</a> on <a href="https://unsplash.com/s/photos/sofa?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
         answer: "이것은 소파예요",
       },
       {
         prompt: "What is that? (a door)",
         image: "thatIsADoor.jpg",
         alt: "Picture of a door",
         credit: `<span>Photo by <a href="https://unsplash.com/@allthestars?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Sophie Dale</a> on <a href="https://unsplash.com/s/photos/door?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
         answer: "저것은 문이에요",
       },
     ],
    "1-2.1": [
      {
        prompt: "What do you have? (pen)",
        image: "iHaveAPen.jpg",
        alt: "Words:Person has a pen", 
        credit: `<span>Photo by <a href="https://unsplash.com/@conscious_design?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Conscious Design</a> on <a href="https://unsplash.com/s/photos/person-with-pen?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,  
        answer: "저는 펜이 있어요",
      },
      {
        prompt: "What do you have? (car)",
        image: "thatIsACar.jpg",
        alt: "Picture of a Car",
        credit: `<span>Photo by <a href="https://unsplash.com/@eduardoflorespe?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Eduardo Flores</a> on <a href="https://unsplash.com/s/photos/car?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "저는 차가 있어요",
      },
      {
        prompt: "What do you have? (magazine)",
        image: "magazine.jpg",
        alt: "Person holding a magazine",
        credit: `<span>Photo by <a href="https://unsplash.com/@trueagency?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">True Agency</a> on <a href="https://unsplash.com/s/photos/magazine?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "저는 잡지가 있어요",
      },
      {
        prompt: "What do you have? (backpack)",
        image: "backpack.jpg",
        alt: "Picture of a backpack",
        credit: `<span>Photo by <a href="https://unsplash.com/@trueagency?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">True Agency</a> on <a href="https://unsplash.com/s/photos/backpack?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "저는 가방이 있어요",
      },
      {
        prompt: "Where are you? (school)",
        image: "school.jpg",
        alt: "Picture of school",
        credit: `<span>Photo by <a href="https://unsplash.com/@element5digital?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Element5 Digital</a> on <a href="https://unsplash.com/photos/OyCl7Y4y0Bk?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "저는 학교에 있어요",
      },
      {
        prompt: "Where are you? (Canada) Is Canada a country?",
        image: "canada.jpg",
        alt: "Picture of canada",
        credit: `<span>Photo by <a href="https://unsplash.com/@britishlibrary?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">British Library</a> on <a href="https://unsplash.com/s/photos/canada-map?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "저는 캐나다에 있어요. 네 캐나다는 나라예요",
      },
      {
        prompt: "Where are you? (in front of the school) Where is the hotel? (next to the school)",
        image: "infrontOfSchool.jpg",
        alt: "Picture of a bus infront of a school",
        credit: `<span>Photo by <a href="https://unsplash.com/@sapegin?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Artem Sapegin</a> on <a href="https://unsplash.com/s/photos/in-front-of-school?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "저는 학교 앞에 있어요. 호텔는 학교 옆에 있어요",
      },
      {
        prompt: "Where are you? (behind the school)",
        image: "behindSchool.jpg",
        alt: "Picture of bus behind a building",
        credit: `<span>Photo by <a href="https://unsplash.com/@eduardoflorespe?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Eduardo Flores</a> on <a href="https://unsplash.com/s/photos/car?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "저는 학교 뒤에 있어요",
      },
      {
        prompt: "Where are you? (beside the school)",
        image: "besideSchool.jpg",
        alt: "Picture of a person beside the school",
        credit: `<span>Photo by <a href="https://unsplash.com/@vheath?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Victoria Heath</a> on <a href="https://unsplash.com/s/photos/beside-of-school?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "저는 학교 옆에 있어요",
      },
      {
        prompt: "Where are you? (inside the bank)",
        image: "insideBank.jpg",
        alt: "Picture of a Bank",
        credit: `<span>Photo by <a href="https://unsplash.com/@alexmotoc?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Alex Motoc</a> on <a href="https://unsplash.com/s/photos/bank?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "저는 은행 안에 있어요",
      },
      {
        prompt: "Where is the dog? (inside the house)",
        image: "dogInHouse.jpg",
        alt: "Picture of a dog in a house",
        credit: `<span>Photo by <a href="https://unsplash.com/@wadeaustinellis?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Wade Austin Ellis</a> on <a href="https://unsplash.com/s/photos/dog-in-a-house?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "개는 집 안에 있어요",
      },
      {
        prompt: "Where is the cat? (under the chair)",
        image: "catUnderChair.jpg",
        alt: "Picture of a chair with words cat under the chair",
        credit: `<span>Photo by <a href="https://unsplash.com/@jontyson?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Jon Tyson</a> on <a href="https://unsplash.com/s/photos/under-a-chair?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "고양이는 의자 밑에 있어요",
      },
      {
        prompt: "Where is the restaurant (next to the bank)",
        image: "restarant.jpg",
        alt: "Picture of a restarant.",
        credit: `<span>Photo by <a href="https://unsplash.com/@adrienolichon?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Adrien Olichon</a> on <a href="https://unsplash.com/s/photos/restaurant?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "식당은 은행 옆에 있어요",
      },
      {
        prompt: "Where is the cat? (behind the house) (“compared to the dog in-front of the house)",
        image: "catbehindHouse.jpg",
        alt: "Picture of a cat. Where is the cat? behind the house.",
        credit: `<span>Photo by <a href="https://unsplash.com/@snowboardinec?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Max Baskakov</a> on <a href="https://unsplash.com/s/photos/cat-behind-house?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "고양이는 집 뒤에 있어요",
      },
      {
        prompt: "Where is the cat? (behind the house) (“just stating a fact, not comparing anything)",
        image: "catbehindHouse.jpg",
        alt: "Picture of a cat. Where is the cat? behind the house.",
        credit: `<span>Photo by <a href="https://unsplash.com/@snowboardinec?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Max Baskakov</a> on <a href="https://unsplash.com/s/photos/cat-behind-house?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "고양이가 집 뒤에 있어요",
      },
    ],
    "1-2.2":[
      {
        prompt: "Where are you? (Canada) Is Canada a country? ",
        image: "canada.jpg",
        alt: "Picture of canada",
        credit: `<span>Photo by <a href="https://unsplash.com/@britishlibrary?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">British Library</a> on <a href="https://unsplash.com/s/photos/canada-map?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "저는 개나다에 있어요. 네, 개나다는 나라예요",

      },
      {
        prompt: "Where are you? (behind the window)",
        image: "window.jpg",
        alt: "Picture of a window.",
        credit: `<span>Photo by <a href="https://unsplash.com/@danielle_dolson?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Danielle Dolson</a> on <a href="https://unsplash.com/s/photos/window?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "저는 창문 뒤에 있어요",

      },
      {
        prompt: "Where are you? (room)",
        image: "room.jpg",
        alt: "Picture of a room.",
        credit: `<span>Photo by <a href="https://unsplash.com/@fromitaly?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Francesca Tosolini</a> on <a href="https://unsplash.com/s/photos/room?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "저는 방에 있어요",
      },
      {
        prompt: "What is this? (refrigerator)",
        image: "refrigerator.jpg",
        alt: "Picture of a fridge",
        credit: `<span>Photo by <a href="https://unsplash.com/@giuliahetherington?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Giulia Hetherington</a> on <a href="https://unsplash.com/s/photos/refrigerator?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "이긋은 냉장고예요",
      },
      {
        prompt: "Where is the puppy? (in the house)",
        image: "puppyInHouse.jpg",
        alt: "Picture of a puppy.",
        credit: `<span>Photo by <a href="https://unsplash.com/@picsea?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Picsea</a> on <a href="https://unsplash.com/s/photos/puppy-in-house?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "강아지는 집에 있어요",
      },
      {
        prompt: "The mouse is on top of a book.  Where is the mouse?",
        image: "mouse.jpg",
        alt: "Picture of a mouse.",
        credit: `<span>Photo by <a href="https://unsplash.com/@yunu_dinata?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Yunu Dinata</a> on <a href="https://unsplash.com/s/photos/mouse?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "쥐는 책 위에 있어요",
      },
      {
        prompt: "What do you have? (phone)",
        image: "phone.jpg",
        alt: "Picture of a phone.",
        credit: `<span>Photo by <a href="https://unsplash.com/@quinoal?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Quino Al</a> on <a href="https://unsplash.com/s/photos/phone?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "저는 전화기가 있어요",
      },
      {
        prompt: "What do you have? (coffee)",
        image: "coffee.jpg",
        alt: "Picture of coffee.",
        credit: `<span>Photo by <a href="https://unsplash.com/@nate_dumlao?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Nathan Dumlao</a> on <a href="https://unsplash.com/s/photos/coffee?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "저는 커피가 있어요",
      },
      {
        prompt: "What is this? (television)",
        image: "television.jpg",
        alt: "Picture of a television.",
        credit: `<span>Photo by <a href="https://unsplash.com/@sveninho?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Sven Scheuermeier</a> on <a href="https://unsplash.com/s/photos/television?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "이것은 텔레비전이에요",
      },
      {
        prompt: "Is USA a country? ",
        image: "usa.jpg",
        alt: "Picture of a the usa.",
        credit: `<span>Photo by <a href="https://unsplash.com/@claybanks?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Clay Banks</a> on <a href="https://unsplash.com/s/photos/map-usa?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "네, 미국은 나라에요",
      },
      {
        prompt: "Where are you? (in front of the hotel) What is that? (a building)",
        image: "hotel.jpg",
        alt: "Picture of a hotel.",
        credit: `<span>Photo by <a href="https://unsplash.com/@martenbjork?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Marten Bjork</a> on <a href="https://unsplash.com/s/photos/hotel?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "저는 호텔 압에 있어요. 저것은 건물이에요",
      },
      {
        prompt: "Are you there or here? (here)",
        image: "phone.jpg",
        alt: "Picture of a phone.",
        credit: `<span>Photo by <a href="https://unsplash.com/@quinoal?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Quino Al</a> on <a href="https://unsplash.com/s/photos/phone?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "저는 여기 있어요",
      },
    ],
    "1-3.1": [
      {
        prompt: "What do you make? (a cake)",
        image: "cake.jpg",
        alt: "Picture of a cake", 
        credit: `<span>Photo by <a href="https://unsplash.com/@americanheritagechocolate?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">American Heritage Chocolate</a> on <a href="https://unsplash.com/?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,  
        answer: "저는 케이크를 만들어요",
      },
      {
        prompt: "What do you want? (a boat)",
        image: "boat.jpg",
        alt: "Picture of a Boat",
        credit: `<span>Photo by <a href="https://unsplash.com/@gautamkrishnan?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Gautam Krishnan</a> on <a href="https://unsplash.com/s/photos/boat?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "저는 배를 원해요",
      },
      {
        prompt: "What do you speak? (Korean)",
        image: "koreanWriting.jpg",
        alt: "Picture of Korean writing",
        credit: `<span>Photo by <a href="https://unsplash.com/@tsuyuri104?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Tsuyuri Hara</a> on <a href="https://unsplash.com/s/photos/korean?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "저는 한국어를 말해요",
      },
      {
        prompt: "What do you close? (the door)",
        image: "openDoor.jpg",
        alt: "Picture of an open door",
        credit: `<span>Photo by <a href="https://unsplash.com/@pechka?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Dima Pechurin</a> on <a href="https://unsplash.com/s/photos/door?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "저는 문을 닫아요",
      },
      {
        prompt: "What do you open? (the window)",
        image: "window.jpg",
        alt: "Picture of an closed window",
        credit: `<span>Photo by <a href="https://unsplash.com/@danielle_dolson?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Danielle Dolson</a> on <a href="https://unsplash.com/s/photos/window?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "저는 창문을 열어요",
      },
      {
        prompt: "Do you understand? (Yes….)",
        image: "manHoldingLightBulb.jpg",
        alt: "Man holding a light bulb",
        credit: `<span>Photo by <a href="https://unsplash.com/@pavement_special?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Riccardo Annandale</a> on <a href="https://unsplash.com/s/photos/light-bulb?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 저는 이해해요",
      },
      {
        prompt: "Where do you go? (to the park)",
        image: "park.jpg",
        alt: "Picture of a park",
        credit: `<span>Photo by <a href="https://unsplash.com/@mbenna?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Mike Benna</a> on <a href="https://unsplash.com/s/photos/park?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "저는 공원에 가요",
      },
      {
        prompt: "Are you beautiful? (Yes …..)",
        image: "womanInWeddingDress.jpg",
        alt: "Woman in a wedding dress",
        credit: `<span>Photo by <a href="https://unsplash.com/@chuttersnap?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">CHUTTERSNAP</a> on <a href="https://unsplash.com/s/photos/beautiful-person?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 저는 아름다워요",
      },
      {
        prompt: "Are you small? (Yes….)",
        image: "sleepingBaby.jpg",
        alt: "Picture of a sleeping baby",
        credit: `<span>Photo by <a href="https://unsplash.com/@peter_oslanec?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Peter Oslanec</a> on <a href="https://unsplash.com/s/photos/baby?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 저는 작아요",
      },
      {
        prompt: "Is this bus big? (yes…..)",
        image: "infrontOfSchool.jpg",
        alt: "Picture of a big bus",
        credit: `<span>Photo by <a href="https://unsplash.com/@sapegin?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Artem Sapegin</a> on <a href="https://unsplash.com/s/photos/in-front-of-school?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 이 버스는 커요",
      },
      {
        prompt: "Is the hospital new? (Yes…)",
        image: "hospital.jpg",
        alt: "Picture of a a hospital",
        credit: `<span>Photo by <a href="https://unsplash.com/@daanstevens?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Daan Stevens</a> on <a href="https://unsplash.com/s/photos/hospital?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 그 병원은 새로워요",
      },
      {
        prompt: "Is the park really small? (Yes…..)",
        image: "smallPark.jpg",
        alt: "Picture of a small park",
        credit: `<span>Photo by <a href="https://unsplash.com/@sigmund?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Sigmund</a> on <a href="https://unsplash.com/s/photos/small-park?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 이 공원은 매우 작아요",
      },
      {
        prompt: "Is that person fat? (Yes…)",
        image: "fatPerson.jpg",
        alt: "Picture of 3 plus size woman.",
        credit: `<span>Photo by <a href="https://unsplash.com/@canweallgo?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">AllGo - An App For Plus Size People</a> on <a href="https://unsplash.com/s/photos/fat-person?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 그 사람은 뚱뚱해요",
      },
      {
        prompt: "Is the teacher’s car big? (Yes…)What do you want? (the teacher’s car)",
        image: "thatIsACar.jpg",
        alt: "Picture of a car.",
        credit: `<span>Photo by <a href="https://unsplash.com/@eduardoflorespe?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Eduardo Flores</a> on <a href="https://unsplash.com/s/photos/car?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 선생님의 차는 커요. 저는 선생님의 차를 원해요",
      },
      {
        prompt: "Is your finger long? (Yes….)",
        image: "longFinger.jpg",
        alt: "Picture of a long finger.",
        credit: `<span>Photo by <a href="https://unsplash.com/@randominstitute?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Random Institute</a> on <a href="https://unsplash.com/s/photos/finger?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 저의 손가락은 길어요",
      },
      {
        prompt: "Is that woman’s eye’s beautiful? (yes..)",
        image: "beautifulEyes.jpg",
        alt: "Picture of a woman's beautiful eyes.",
        credit: `<span>Photo by <a href="https://unsplash.com/@alexandruz?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Alexandru Zdrobău</a> on <a href="https://unsplash.com/s/photos/eyes?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 그 여자의 눈은 아름다워요",
      },
      {
        prompt: "Do you meet your friend? (Yes..)",
        image: "friendsClapping.jpg",
        alt: "Picture friends clapping hands.",
        credit: `<span>Photo by <a href="https://unsplash.com/@jtylernix?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Tyler Nix</a> on <a href="https://unsplash.com/s/photos/friend?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 저는 저의 친구를 만나요) or 저는 친구를 만나요",
      },
      {
        prompt: "Is this food good? (Yes…) Do you like this food? (Yes…)",
        image: "food.jpg",
        alt: "Picture of food.",
        credit: `<span>Photo by <a href="https://unsplash.com/@therachelstory?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Rachel Park</a> on <a href="https://unsplash.com/s/photos/food?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 이 음식은 좋아요. 네, 저는 이 음식을 좋아해요",
      },
      {
        prompt: "Is that teacher good? (Yes…). Do you like that teacher? (Yes…)  Does the teacher like us? (Yes..)",
        image: "iAmATeacher.jpg",
        alt: "Picture of woman teacher.",
        credit: `<span>Photo by <a href="https://unsplash.com/@windows?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Windows</a> on <a href="https://unsplash.com/s/photos/teacher-points-to-herself?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 그 선생님은 좋아요.  네, 저는 그 선생님을 좋아해요. 네, 선생님은 우리를 좋아해요",
      },
      {
        prompt: "Is this school good? (Yes…)",
        image: "school.jpg",
        alt: "Picture of school books.",
        credit: `<span>Photo by <a href="https://unsplash.com/@element5digital?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Element5 Digital</a> on <a href="https://unsplash.com/photos/OyCl7Y4y0Bk?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 이 학교는 좋아요",
      },
      {
        prompt: "Do you’all like me? (Yes…)",
        image: "girlGivingHeartSign.jpg",
        alt: "Picture of a girl giving a heart sign.",
        credit: `<span>Photo by <a href="https://unsplash.com/@lucidistortephoto?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Alfonso Scarpa</a> on <a href="https://unsplash.com/s/photos/people-with-hearts?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 우리는 너를 좋아해",
      },
      {
        prompt: "Is our teacher a man? (Yes…)",
        image: "manTeacher.jpg",
        alt: "Picture of a man teacher.",
        credit: `<span>Photo by <a href="https://unsplash.com/@macroman?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Immo Wegmann</a> on <a href="https://unsplash.com/s/photos/man-teacher?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 우리 선생님은 남자예요",
      },
      {
        prompt: "Is our house big? (Yes…)",
        image: "thisIsAHouse.jpg",
        alt: "Picture of a big house.",
        credit: `<span>Photo by <a href="https://unsplash.com/@jacquesbopp?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Jacques Bopp</a> on <a href="https://unsplash.com/s/photos/house?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 우리 집은 커요",
      },
    ],
    "1-3.2":[
      {
        prompt: "Are you at the airport? (Yes…)",
        image: "planLanding.jpg",
        alt: "Picture of a plane landing.",
        credit: `<span>Photo by <a href="https://unsplash.com/@zhpix?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Pascal Meier</a> on <a href="https://unsplash.com/s/photos/airport?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "네, 저는 공항에 있어요",
      },
      {
        prompt: "Is your head big? (Yes…)",
        image: "bigHeadBaby.jpg",
        alt: "Picture of a big headed baby",
        credit: `<span>Photo by <a href="https://unsplash.com/@spanic?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Damir Spanic</a> on <a href="https://unsplash.com/s/photos/big-head?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "네, 저의 머리는 커요",
      },
      {
        prompt: "Is your leg long? (Yes…)",
        image: "longLegsWoman.jpg",
        alt: "Picture of a woman with long legs.",
        credit: `<span>Photo by <a href="https://unsplash.com/@joanna_nix?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Joanna Nix-Walkup</a> on <a href="https://unsplash.com/s/photos/long-legs?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "네, 저의 다리는 길어요",
      },
      {
        prompt: "Is your ear beautiful? (Yes…)",
        image: "womansEars.jpg",
        alt: "Picture of a woman's ears.",
        credit: `<span>Photo by <a href="https://unsplash.com/@fideletty?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Etty Fidele</a> on <a href="https://unsplash.com/s/photos/pretty-ears?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "네, 귀는 아름다워요",
      },
      {
        prompt: "Is your arm fat? (Yes…) Is your stomach fat? (Yes…)",
        image: "fatPerson.jpg",
        alt: "Picture of 3 plus size woman.",
        credit: `<span>Photo by <a href="https://unsplash.com/@canweallgo?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">AllGo - An App For Plus Size People</a> on <a href="https://unsplash.com/s/photos/fat-person?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "네, 팔은 똥똥헤요. 네, 배는 뚱뚱해요",
      },
      {
        prompt: "Is your mouth small? (Yes…)",
        image: "smallMouth.jpg",
        alt: "Picture of a small mouth.",
        credit: `<span>Photo by <a href="https://unsplash.com/@inagarbe?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Ina Garbé</a> on <a href="https://unsplash.com/s/photos/small-mouth?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "네, 입은 작아요",
      },
      {
        prompt: "What do you eat? (food) Is this food cheap? (yes…)",
        image: "food.jpg",
        alt: "Picture of food.",
        credit: `<span>Photo by <a href="https://unsplash.com/@therachelstory?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Rachel Park</a> on <a href="https://unsplash.com/s/photos/food?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "저는 음식를 먹어요. 네, 이 음식은 싸요",
      },
      {
        prompt: "Where do you go? (home(house))",
        image: "thisIsAHouse.jpg",
        alt: "Picture of a house.",
        credit: `<span>Photo by <a href="https://unsplash.com/@jacquesbopp?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Jacques Bopp</a> on <a href="https://unsplash.com/s/photos/house?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "저는 집에 가요",
      },
      {
        prompt: "Is this building old? (Yes…)",
        image: "castle.jpg",
        alt: "Picture of a castle.",
        credit: `<span>Photo by <a href="https://unsplash.com/@waldemarbrandt67w?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Waldemar Brandt</a> on <a href="https://unsplash.com/s/photos/old-building?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "네, 이 건물은 낡아요",
      },
      {
        prompt: "Is this boat really expensive? (yes…) Do you have a boat? (yes..)",
        image: "boat.jpg",
        alt: "Picture of a boat.",
        credit: `<span>Photo by <a href="https://unsplash.com/@gautamkrishnan?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Gautam Krishnan</a> on <a href="https://unsplash.com/s/photos/boat?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "네, 이 배는 아주 비싸요. 네, 저는 배가 있어요",
      },
      {
        prompt: "Is the hospital a building? (Yes…)",
        image: "hospital.jpg",
        alt: "Picture of a hospital.",
        credit: `<span>Photo by <a href="https://unsplash.com/@daanstevens?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Daan Stevens</a> on <a href="https://unsplash.com/s/photos/hospital?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "네, 병원은 건물이에요",
      },
    ],
    "1-4.1":[
      {
        prompt: "What do you say when someone is going away (bye)  What do you say when someone is staying (bye)",
        image: "personWavingGoodbye.jpg",
        alt: "person Waving Goodbye",
        credit: `<span>Photo by <a href="https://unsplash.com/@typebymayank?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Mayank Baranwal</a> on <a href="https://unsplash.com/s/photos/hello?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "안녕히 가세요  안녕히 계세요",
      },
      {
        prompt: "When you meet someone for the first time, it’s good to say things like (Hello, Nice to meet you) (What is your name?) (Where are you from?)",
        image: "friendsClapping.jpg",
        alt: "Picture friends clapping hands.",
        credit: `<span>Photo by <a href="https://unsplash.com/@jtylernix?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Tyler Nix</a> on <a href="https://unsplash.com/s/photos/friend?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "만나서 반갑습니다 / 이름이 뭐예요? / 어디에서 왔어요?",
      },
      {
        prompt: "You need to get someone’s attention you say (Excuse me)",
        image: "personWavingGoodbye.jpg",
        alt: "person Waving Goodbye",
        credit: `<span>Photo by <a href="https://unsplash.com/@typebymayank?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Mayank Baranwal</a> on <a href="https://unsplash.com/s/photos/hello?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "실례합니다",
      },
      {
        prompt: "You accidentally bump into someone you say (Sorry)",
        image: "muscleguylooksdistressed.jpg",
        alt: "A muscle guy looks distressed.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@spanic?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Damir Spanic</a> on <a href="https://unsplash.com/s/photos/sorry?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "미안합니다",
      },
      {
        prompt: "이름이 뭐예요?  (My name is _______)     어디에서 왔어요 (I’m from _________)",
        image: "thatIsAName.jpg",
         alt: "Picture of a name on a name tag",
         credit: `<span>Photo by <a href="https://unsplash.com/@_blahblake?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Blake Barlow</a> on <a href="https://unsplash.com/s/photos/name-tag?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
         answer: "저의 이름은 ______이에요     저는 _______에서 왔어요",
      },
      {
        prompt: "Is the food expensive? (Yes…)     Do you eat expensive food? (Yes…)   Do you like expensive food? (Yes…)  Is expensive food delicious? (Yes…)   What do you eat? (delicious food)   Do you eat a lot of food? (Yes….)  Is there a lot of food? (Yes…)",
        image: "expensiveFood.jpg",
        alt: "Picture of expensive food",
        credit: `<span>Photo by <a href="https://unsplash.com/@louishansel?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Louis Hansel @shotsoflouis</a> on <a href="https://unsplash.com/s/photos/expensive-food?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "음식은 비싸요. 저는 비싼 음식을 먹어요. 저는 비싼 음식을 좋아해요. 비싼 음식은 맛있어요. 저는 맛있는 음식을 먹어요. 저는 많은 음식을 먹어요. 음식이 많아요",
      },
      {
        prompt: "Where do you go? (to the small house)  Is the house small? (Yes..)",
        image: "smallHouse.jpg",
        alt: "Pic of small house",
        credit: `<span>Photo by <a href="https://unsplash.com/@heftiba?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Toa Heftiba</a> on <a href="https://unsplash.com/s/photos/small-house?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "저는 작은 집에 가요.  그 집은 작아요",
      },
      {
        prompt: "What do you want? (a big car) Is this car big? (Yes…)",
        image: "bigCar.jpg",
        alt: "Picture of a old big car",
        credit: `<span>Photo by <a href="https://unsplash.com/@markusspiske?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Markus Spiske</a> on <a href="https://unsplash.com/s/photos/big-car?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "저는 큰 차를 원해요. 이 차는 커요",
      },
      {
        prompt: "Who do you meet? (a handsome man)",
        image: "handsomeMan.jpg",
        alt: "a handsome man",
        credit: `<span>Photo by <a href="https://unsplash.com/@alexiby?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Alex Iby</a> on <a href="https://unsplash.com/s/photos/handsome-man?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "저는 잘생긴 남자를 만나요",
      },
      {
        prompt: "What do you have? (a lot of money)",
        image: "paperMoney.jpg",
        alt: "paper money",
        credit: `<span>Photo by <a href="https://unsplash.com/@ninjason?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Jason Leung</a> on <a href="https://unsplash.com/s/photos/money?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "저는 많은 돈이 있어요",
      },
      {
        prompt: "Who do you meet? (a fat student)",
        image: "fatPerson.jpg",
        alt: "Picture of 3 plus size woman.",
        credit: `<span>Photo by <a href="https://unsplash.com/@canweallgo?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">AllGo - An App For Plus Size People</a> on <a href="https://unsplash.com/s/photos/fat-person?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "저는 뚱뚱한 학생을 만나요",
      },
      {
        prompt: "What does the man eat? (food)",
        image: "manEatingFood.jpg",
        alt: "Man eating food.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@sanderdalhuisen?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Sander Dalhuisen</a> on <a href="https://unsplash.com/s/photos/man-eating-food?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "남자는 음식을 먹어요",
      },
      {
        prompt: "The happy girl is inside what? (the small car)",
        image: "girlinsidecar.jpg",
        alt: "girl inside car.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@wendellfernandes?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Wendell Fernandes</a> on <a href="https://unsplash.com/s/photos/girl-inside-car?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "행복한 여자는 작은 차 안에 있어요",
      },
      {
        prompt: "That man is what? (a funny man)",
        image: "manlaughing.jpg",
        alt: "man laughing.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@harrycunnningham1?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Harry Cunningham</a> on <a href="https://unsplash.com/s/photos/funny-man?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "그 남자는 재미있는 남자예요",
      },
      {
        prompt: "I have a lot of what? ( wives)",
        image: "brides.jpg",
        alt: "brides.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@dre0316?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Andre Hunter</a> on <a href="https://unsplash.com/s/photos/brides?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "저는 많은 아내가 있어요",
      },
      {
        prompt: "There is a lot of what? (people)",
        image: "people.jpg",
        alt: "people.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@derstudi?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Timon Studler</a> on <a href="https://unsplash.com/s/photos/people?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "사람이 많아요",
      },
      {
        prompt: "Do you too speak Korean? (Yes…) (In addition to other people)",
        image: "koreanworddream.jpg",
        alt: "korean word dream.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@insungyoon?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">insung yoon</a> on <a href="https://unsplash.com/s/photos/korean-words?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "저도 한국어를 말해요",
      },
      {
        prompt: "Do you speak Korean too? (Yes…) (in addition to other languages)",
        image: "koreanworddream.jpg",
        alt: "korean word dream.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@insungyoon?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">insung yoon</a> on <a href="https://unsplash.com/s/photos/korean-words?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "저는 한국어도 말해요",
      },
      {
        prompt: "Do you too eat apples? (Yes…) (In addition to other people)",
        image: "personwithapples.jpg",
        alt: "person with apples.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@missnjc?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Natalie Grainger</a> on <a href="https://unsplash.com/s/photos/apples?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "저도 사과를 먹어요",
      },
      {
        prompt: "Do you eat apples too? (Yes…) (in addition to other apples)",
        image: "personwithapples.jpg",
        alt: "person with apples.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@missnjc?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Natalie Grainger</a> on <a href="https://unsplash.com/s/photos/apples?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "저는 사과도 먹어요",
      },
      {
        prompt: "You too know that? (Yes..)",
        image: "manHoldingLightBulb.jpg",
        alt: "Man holding a light bulb",
        credit: `<span>Photo by <a href="https://unsplash.com/@pavement_special?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Riccardo Annandale</a> on <a href="https://unsplash.com/s/photos/light-bulb?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: " 저도 그것을 알아요",
      },
      {
        prompt: "You too are tired? (Yes..)",
        image: "bookoverface.jpg",
        alt: "book over face.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@tonny_tran?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Tony Tran</a> on <a href="https://unsplash.com/s/photos/tired?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: " 저도 피곤해요",
      },
      {
        prompt: "Is your daughter happy too? (Yes…)",
        image: "girlinsidecar.jpg",
        alt: "girl inside car.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@wendellfernandes?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Wendell Fernandes</a> on <a href="https://unsplash.com/s/photos/girl-inside-car?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "저의 딸도 행복해요",
      },
    ],
    "1-4.2":[
      {
        prompt: "Does the child have a bicycle? (Yes…)",
        image: "childonbicycle.jpg",
        alt: "child on bicycle.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@liz99?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">童 彤</a> on <a href="https://unsplash.com/s/photos/child-on-bicycle?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "녜, 아이는 자전거가 있어요",
      },
      {
        prompt: "Does the son practice English? (Yes…)",
        image: "opendiary.jpg",
        alt: "open diary.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@dtravisphd?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">David Travis</a> on <a href="https://unsplash.com/s/photos/english-writing?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "네, 아들는 영어를 연습해요",
      },
      {
        prompt: "Where is the sad father? (in the steet)거리",
        image: "maninroad.jpg",
        alt: "man in road.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@jeremybishop?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Jeremy Bishop</a> on <a href="https://unsplash.com/s/photos/man-in-street?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "슬픈 아버지는 거리에 있어요",
      },
      {
        prompt: "Is that an ugly taxi? (Yes…)",
        image: "uglytaxi.jpg",
        alt: "ugly taxi.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@huefnerdesign?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Tim Hüfner</a> on <a href="https://unsplash.com/s/photos/big-car?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "네, 저것은 못생긴 택시예요",
      },
      {
        prompt: "Is the bus stop in the street? (yes…)  길",
        image: "busstopinstreet.jpg",
        alt: "bus stop in street.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@northwoodn?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Li Lin</a> on <a href="https://unsplash.com/s/photos/bus-stop?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "네, 버스 정류장은 길에 있어요",
      },
      {
        prompt: "Does the mother have a different letter? (Yes…)",
        image: "letter.jpg",
        alt: "a letter.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@waros?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Wendy Aros-Routman</a> on <a href="https://unsplash.com/s/photos/letter?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "네, 어머니는 다른 편지가 있어요",
      },
      {
        prompt: "Does the husband have water on the train? (Yes…)",
        image: "peopleontrain.jpg",
        alt: "people on train.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@francesco_ungaro?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Francesco Ungaro</a> on <a href="https://unsplash.com/s/photos/man-in-train?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "네, 남편는 열차에 물이 있어요",
      },
      {
        prompt: "Is breakfast delicious? (yes…) Is the meal delicious? (Yes…) ",
        image: "food.jpg",
        alt: "Picture of food.",
        credit: `<span>Photo by <a href="https://unsplash.com/@therachelstory?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Rachel Park</a> on <a href="https://unsplash.com/s/photos/food?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 아침식사는 맛있어요.  네, 식사는 맛있어요. ",
      },
      {
        prompt: "Does the cat come to the train station?",
        image: "catonfainttraintracks.jpg",
        alt: "cat on faint train tracks.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@miklevasilyev?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">MIKHAIL VASILYEV</a> on <a href="https://unsplash.com/s/photos/cat-at-train-station?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "네, 고양이는 역에 와요",
      },
      {
        prompt: "Does the child walk? (yes)",
        image: "childwalking.jpg",
        alt: "child walking.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@jxk?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Jan Kopřiva</a> on <a href="https://unsplash.com/s/photos/child-walking?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "네, 아이는 걸어요",
      },
      {
        prompt: "Are you there or here? (there)",
        image: "personpointingthere.jpg",
        alt: "person pointing there.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@minusculemarie?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Marie-Michèle Bouchard</a> on <a href="https://unsplash.com/s/photos/there?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "저는 거기 있어요",
      },
      {
        prompt: "Does this child too, dance now? (yes..)",
        image: "childdancing.jpg",
        alt: "child dancing.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@monroefiles?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Gabby Orcutt</a> on <a href="https://unsplash.com/s/photos/child-dancing?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "네, 지금, 이 아이도 춤춰요",
      },
      {
        prompt: "Is the taste delicious? (Yes…)",
        image: "food.jpg",
        alt: "Picture of food.",
        credit: `<span>Photo by <a href="https://unsplash.com/@therachelstory?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Rachel Park</a> on <a href="https://unsplash.com/s/photos/food?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 맛이 맛있어요.",
      },
      {
        prompt: "What opens windows? (Hands…)",
        image: "window.jpg",
        alt: "Picture of a window.",
        credit: `<span>Photo by <a href="https://unsplash.com/@danielle_dolson?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Danielle Dolson</a> on <a href="https://unsplash.com/s/photos/window?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "손는 창문을 열어요",
      },
      {
        prompt: "Do you learn Korean now?",
        image: "koreanWriting.jpg",
        alt: "Picture of Korean writing",
        credit: `<span>Photo by <a href="https://unsplash.com/@tsuyuri104?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Tsuyuri Hara</a> on <a href="https://unsplash.com/s/photos/korean?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 저는 한국어를 지금 배워요",
      },
    ],
    "1-5.1":[
      {
        prompt: "Who do you meet? (a friend-Diary form). Who did you meet? (friends-Diary form)",
        image: "friendsClapping.jpg",
        alt: "Picture friends clapping hands.",
        credit: `<span>Photo by <a href="https://unsplash.com/@jtylernix?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Tyler Nix</a> on <a href="https://unsplash.com/s/photos/friend?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "나는 친구를 만난다. 나는 친구를 만났다 ",
      },
      {
        prompt: "What do you understand? (that- Diary form)",
        image: "manHoldingLightBulb.jpg",
        alt: "Man holding a light bulb",
        credit: `<span>Photo by <a href="https://unsplash.com/@pavement_special?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Riccardo Annandale</a> on <a href="https://unsplash.com/s/photos/light-bulb?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "나는 그것을 이해한다 ",
      },
      {
        prompt: "What do you learn? (Korean-Diary form). Will you learn? (yes...-Diary form  - uncommon future form) What did you study? (Korean-Diary form),  What did you study? (Korean-Diary form (where  하 and 여 are not merged to formed 해)",
        image: "koreanWriting.jpg",
        alt: "Picture of Korean writing",
        credit: `<span>Photo by <a href="https://unsplash.com/@tsuyuri104?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Tsuyuri Hara</a> on <a href="https://unsplash.com/s/photos/korean?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "나는 한국어를 배운다.  나는 배우겠다.  나는 한국어를 공부했다.  나는 한국어를 공부하였다  ",
      },
      {
        prompt: "Where do you go? (home(house-Diary form))",
        image: "thisIsAHouse.jpg",
        alt: "Picture of a house.",
        credit: `<span>Photo by <a href="https://unsplash.com/@jacquesbopp?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Jacques Bopp</a> on <a href="https://unsplash.com/s/photos/house?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
       answer: "나는 집에 간다 ",
      },
      {
        prompt: "What did you eat? (rice-Diary form). Will you eat? (yes...-Diary form less - uncommon future form) What was delicious? (that food-Diary form).  What will be delicious? (that thing...Diary form). Will you be hungry? (Yes...-Diary form)",
        image: "food.jpg",
        alt: "Picture of food.",
        credit: `<span>Photo by <a href="https://unsplash.com/@therachelstory?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Rachel Park</a> on <a href="https://unsplash.com/s/photos/food?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "나는 밥을 먹었다. 나는 먹겠다. 그 음식은 맛있었다.  그것은 맛있겠다.  나는 배고프겠다      ",
      },
      {
        prompt: "What did you close? (door-Diary form)",
        image: "openDoor.jpg",
        alt: "Picture of an open door",
        credit: `<span>Photo by <a href="https://unsplash.com/@pechka?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Dima Pechurin</a> on <a href="https://unsplash.com/s/photos/door?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "나는 문을 닫았다 ",
      },
      {
        prompt: "What did you open? (window-Diary form)",
        image: "window.jpg",
        alt: "Picture of a window.",
        credit: `<span>Photo by <a href="https://unsplash.com/@danielle_dolson?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Danielle Dolson</a> on <a href="https://unsplash.com/s/photos/window?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
         answer: "나는 창문을 열었다 ",
      },
      {
        prompt: "Where did you go? (museum-Diary form)",
        image: "museum.jpg",
        alt: "Picture of museum",
        credit: `<span>Photo by <a href="https://unsplash.com/@anthonydelanoix?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Anthony DELANOIX</a> on <a href="https://unsplash.com/s/photos/museum?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "나는 박물관에 갔다  ",
      },
      {
        prompt: "Who came to the store? (Uncle-Diary form)",
        image: "store.jpg",
        alt: "Picture of a store open",
        credit: `<span>Photo by <a href="https://unsplash.com/@mikepetrucci?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Mike Petrucci</a> on <a href="https://unsplash.com/s/photos/store?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "삼촌은 가게에 왔다  ",
      },
      {
        prompt: "Who learned English? (older brother (of sister)-Diary form)",
        image: "opendiary.jpg",
        alt: "open diary.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@dtravisphd?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">David Travis</a> on <a href="https://unsplash.com/s/photos/english-writing?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "오빠는 영어를 배웠다  ",
      },
      {
        prompt: "Did you throw the ball? (yes…Diary form)",
        image: "tennisball.jpg",
        alt: "Picture of a tennis ball",
        credit: `<span>Photo by <a href="https://unsplash.com/@zahra_rfi96?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Zahra Rafiei</a> on <a href="https://unsplash.com/s/photos/ball?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "나는 공을 던졌다 ",
      },
      {
        prompt: "Did you cross the street?길 (yes...-Diary form)",
        image: "maninroad.jpg",
        alt: "man in road.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@jeremybishop?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Jeremy Bishop</a> on <a href="https://unsplash.com/s/photos/man-in-street?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "나는 길을 건넜다 ",
      },
      {
        prompt: "Will you go? (yes...-Diary form  - uncommon future form)",
        image: "personleaving.jpg",
        alt: "person leaving",
        credit: `<span>Photo by <a href="https://unsplash.com/@mantashesthaven?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Mantas Hesthaven</a> on <a href="https://unsplash.com/s/photos/person-leaving?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "나는 가겠다  ",
      },
      {
        prompt: "Who is beautiful? (that teacher---Diary form) Who was good? (that teacher-Diary form)",
        image: "iAmATeacher.jpg",
        alt: "Picture of Teacher",
        credit: `<span>Photo by <a href="https://unsplash.com/@windows?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Windows</a> on <a href="https://unsplash.com/s/photos/teacher-points-to-herself?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "그 선생님은 아름답다. 그 선생님은 좋았다 ",
      },
      {
        prompt: "What is long? (that street-Diary form).  What was long? (that street-Diary form)",
        image: "maninroad.jpg",
        alt: "man in road.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@jeremybishop?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Jeremy Bishop</a> on <a href="https://unsplash.com/s/photos/man-in-street?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "그 길은 길다. 그 길은 길었다   ",
      },
      {
        prompt: "What is big? (my hand-Diary form)",
        image: "handoverlake.jpg",
        alt: "hand over lake",
        credit: `<span>Photo by <a href="https://unsplash.com/@jeremybishop?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Jeremy Bishop</a> on <a href="https://unsplash.com/s/photos/big-hand?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "나의 손은 크다 ",
      },
      {
        prompt: "What was old? (that restaurant-Diary form (old=something that has existed for a long time)",
        image: "oldrestaurant.jpg",
        alt: "old restaurant",
        credit: `<span>Photo by <a href="https://unsplash.com/@rokjecar?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Rok Zabukovec</a> on <a href="https://unsplash.com/s/photos/old-restaurant?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "그 식당이 오래되었다  ",
      },
      {
        prompt: "What was expensive? (this-Diary form)",
        image: "boat.jpg",
        alt: "Picture of a Boat",
        credit: `<span>Photo by <a href="https://unsplash.com/@gautamkrishnan?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Gautam Krishnan</a> on <a href="https://unsplash.com/s/photos/boat?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "이것은 비쌌다  ",
      },
      {
        prompt: "Who was handsome? (That man-Diary from)",
        image: "handsomeMan.jpg",
        alt: "a handsome man",
        credit: `<span>Photo by <a href="https://unsplash.com/@alexiby?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Alex Iby</a> on <a href="https://unsplash.com/s/photos/handsome-man?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "그 남자는 잘생겼다  ",
      },
      {
        prompt: "Who was fat? (that person-Diary form)",
        image: "fatman.jpg",
        alt: "fat man.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@canweallgo?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">AllGo - An App For Plus Size People</a> on <a href="https://unsplash.com/s/photos/fat-man?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "그 사람은 뚱뚱했다 ",
      },
      {
        prompt: "Will you be happy? (Yes...Diary form)",
        image: "happygirl.jpg",
        alt: "happy girl",
        credit: `<span>Photo by <a href="https://unsplash.com/@ryanmoreno?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Ryan Moreno</a> on <a href="https://unsplash.com/s/photos/happy-person?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "나는 행복하겠다  ",
      },
    ],
    "1-5.2":[
      {
        prompt: "Is that man(old man that you don’t know) dangerous? (yes...Diary form)",
        image: "manwithknife.jpg",
        alt: "man with knife.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@kimdonkey?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Manki Kim</a> on <a href="https://unsplash.com/s/photos/old-man-with-knife?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 그 아저씨는 위험하다",
      },
      {
        prompt: "Does your younger sister have glasses? (yes..)",
        image: "girlwithglasses.jpg",
        alt: "girl with glasses.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@ilienerwise?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Max Ilienerwise</a> on <a href="https://unsplash.com/s/photos/girl-with-classes?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 저의 여동생은 안경이 있어요",
      },
      {
        prompt: "Does your younger brother have a secret? (Yes..)",
        image: "guywithsecret.jpg",
        alt: "guy with secret.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@tinaflour?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Kristina Flour</a> on <a href="https://unsplash.com/s/photos/guy-with-secret?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 저의 남동생은 비밀이 있어요",
      },
      {
        prompt: "Does your aunt (on your mother’s side) have a picture? (yes…)",
        image: "girltakingphoto.jpg",
        alt: "girl taking photo.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@aiony?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Aiony Haust</a> on <a href="https://unsplash.com/s/photos/girl-with-photo?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 저의 이모는 사긴이 있어요",
      },
      {
        prompt: "Does the duck have a tail?(yes…)",
        image: "duck.jpg",
        alt: "duck.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@bruthethe?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Bruno Thethe</a> on <a href="https://unsplash.com/s/photos/duck?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 오리는 꼬리가 있어요",
      },
      {
        prompt: "Does your aunt (on your father’s side) expect a picture? (Yes..)",
        image: "camera.jpg",
        alt: "camera.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@patuphotos?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Patrick</a> on <a href="https://unsplash.com/s/photos/camera?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 저의 고모는 사진을 기대해요",
      },
      {
        prompt: "Is the rain boring? (yes..Diary form). Does your older sister (of sister) like the rain? (no…)",
        image: "rain.jpg",
        alt: "rain.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@anant90?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Anant Jain</a> on <a href="https://unsplash.com/s/photos/rain?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 비는 지루하다. 아니, 나의 언니는 비를 싫어해요",
      },
      {
        prompt: "Does your older brother (of brother) have a stove?",
        image: "stove.jpg",
        alt: "stove.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@ghosttrooper?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Brandon Cormier</a> on <a href="https://unsplash.com/s/photos/stove?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 형은 가스 레인지가 있어요",
      },
      {
        prompt: "Did your younger sibling leave? (yes..Diary form)",
        image: "personleaving.jpg",
        alt: "person leaving",
        credit: `<span>Photo by <a href="https://unsplash.com/@mantashesthaven?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Mantas Hesthaven</a> on <a href="https://unsplash.com/s/photos/person-leaving?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 나의 동생은 떠났다",
      },
      {
        prompt: "Is your older sister (of brother) far away? (yes…Diary form)",
        image: "personfaraway.jpg",
        alt: "person far away.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@claybanks?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Clay Banks</a> on <a href="https://unsplash.com/s/photos/person-far-away?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 누나는 멀다",
      },
    ],
    "1-6.1":[
      {
        prompt: "Do you always eat food in the evening? (Informal low respect)  Do you always eat food in the evening? Do you always eat food in the evening? (Formal High respect)",
        image: "food.jpg",
        alt: "Picture of food.",
        credit: `<span>Photo by <a href="https://unsplash.com/@therachelstory?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Rachel Park</a> on <a href="https://unsplash.com/s/photos/food?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "나는 항상 저녁에 음식을 먹어.  저는 항상 저녁에 음식을 먹어요.  저는 항상 저녁에 음식을 먹습니다. ",
      },
      {
        prompt: "Do you always see your teacher? (Informal low respect) Do you always see your teacher?  Do you always see your teacher? (Formal High respect) ",
        image: "iAmATeacher.jpg",
        alt: "Picture of Teacher",
        credit: `<span>Photo by <a href="https://unsplash.com/@windows?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Windows</a> on <a href="https://unsplash.com/s/photos/teacher-points-to-herself?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`,
        answer: "나는 나의 선생님을 항상 봐.  저는 저의 선생님을 항상 봐요. 저는 저의 선생님을 항상 봅니다 ",
      },
      {
        prompt: "Do you always exercise in the morning? (Informal low respect)  Do you always exercise in the morning?  Do you always exercise in the morning? (Formal High respect) ",
        image: "exercise.jpg",
        alt: "three people running",
        credit: `<span>Photo by <a href="https://unsplash.com/@fitmasu?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Fitsum Admasu</a> on <a href="https://unsplash.com/s/photos/exercise?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "나는 항상 아침에 운동해. 저는 항상 아침에 운동해요.  저는 항상 아침에 운동합니다  ",
      },
      {
        prompt: "Did you eat?  (Informal low respect)  Did you eat?  Did you eat?  (Formal High respect)  ",
        image: "food.jpg",
        alt: "Picture of food.",
        credit: `<span>Photo by <a href="https://unsplash.com/@therachelstory?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Rachel Park</a> on <a href="https://unsplash.com/s/photos/food?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "나는 먹었어. 저는 먹었어요. 저는 먹었습니다",
      },
      {
        prompt: "Did you listen?  (Informal low respect)  Did you listen?   Did you listen?  (Formal High respect) ",
        image: "ear.jpg",
        alt: "picture of an ear",
        credit: `<span>Photo by <a href="https://unsplash.com/@francogio?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Franco Antonio Giovanella</a> on <a href="https://unsplash.com/s/photos/listen?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "나는 들어봤어.  저는 들어봤어요. 저는 들어봤습니다   ",
      },
      {
        prompt: "Did you exercise?  (Informal low respect) Did you exercise?  Did you exercise?  (Formal High respect)  ",
        image: "exercise.jpg",
        alt: "three people running",
        credit: `<span>Photo by <a href="https://unsplash.com/@fitmasu?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Fitsum Admasu</a> on <a href="https://unsplash.com/s/photos/exercise?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "나는 운동했어.  저는 운동했어요.  저는 운동했습니다 ",
      },
      {
        prompt: "Will you eat?  (Informal low respect)  Will you eat?  Will you eat?  (Formal High respect)",
        image: "food.jpg",
        alt: "Picture of food.",
        credit: `<span>Photo by <a href="https://unsplash.com/@therachelstory?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Rachel Park</a> on <a href="https://unsplash.com/s/photos/food?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "나는 먹겠어.  저는 먹겠어요.  저는 먹겠습니다 ",
      },
      {
        prompt: "Will you learn?  (Informal low respect) Will you learn? Will you learn?  (Formal High respect) ",
        image: "learnsign.jpg",
        alt: "learn sign on wall.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@timmossholder?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Tim Mossholder</a> on <a href="https://unsplash.com/s/photos/learn?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "나는 배우겠어.  저는 배우겠어요. 저는 배우겠습니다. ",
      },
    ],
    "1-6.2":[
      {
        prompt: "Did grandfather finish his book?",
        image: "grandfatherwithbook.jpg",
        alt: "grandfather with book.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@aaronandrewang?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Aaron Andrew Ang</a> on <a href="https://unsplash.com/s/photos/old-man?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 할아버지는 책을 끝냈어요",
      },
      {
        prompt: "Does grandmother joke?",
        image: "grandmotherhands.jpg",
        alt: "grandmother hands.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@cristian_newman?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Cristian Newman</a> on <a href="https://unsplash.com/s/photos/old-woman?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 할머니는 농담해요",
      },
      {
        prompt: "Is that older woman (not related to you) too thin?",
        image: "thinwoman.jpg",
        alt: "thin woman.jpg",
        credit: `<span>Photo by <a href="https://unsplash.com/@jairoalzatedesign?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Jairo Alzate</a> on <a href="https://unsplash.com/s/photos/thin-woman?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 그 아주머니는 너무 마라요",
      },
      {
        prompt: "Will you eat tomorrow?  Will you eat today?  Did you eat yesterday? Will you eat the day after tomorrow?",
        image: "food.jpg",
        alt: "Picture of food.",
        credit: `<span>Photo by <a href="https://unsplash.com/@therachelstory?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Rachel Park</a> on <a href="https://unsplash.com/s/photos/food?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>`, 
        answer: "네, 내일 먹겠어요.  네, 오늘 먹겠어요.  네, 어제, 먹었어요.  네, 모레 먹겠어요.",
      },
    ],
 };